# CI/CD pipeline for Inote API
# atsuhikoMochizuki
# 08/05/2024
---
name: CI/CD pipeline for Inote API
'on':
  push:
    branches: ["main"]
jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: Create folder on host for deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p ./Inote_project/web_interface
  build-deploy:
    name: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: npm ci && npm run build
      - name: deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: "./dist/inote-web-interface/"
          target: "/var/www/html"
          #strip_components: 1  # kill-process:
          
         
